### 모임 생성
POST {{host}}/api/meetings
Content-Type: application/json

{
  "startDate": "2022-08-22T22:37:00",
  "endDate": "2022-08-22T22:46:01",
  "place": {
    "summary": "코알라 클라이밍",
    "address": "마포구 월드컵북로 396 누리꿈스퀘어 디지털파빌리온 B1040호",
    "mapLink": "https://naver.me/GKovmE2q"
  }
}

### 모임 리스트 조회
GET {{host}}/api/meetings

### 모임 상세 조회
GET {{host}}/api/meetings/398

### 모임 제거
DELETE {{host}}/api/meetings/100

### 갈게요/못가요
PUT {{host}}/api/meetings/398/attendance
Content-Type: application/json

{
  "wantToAttend": true
}

### 출석/결석 처리
PUT {{host}}/api/meetings/138/users/46/attendance
Content-Type: application/json

{
  "attend": true
}
